export function attachVolumeMenu({anchor,onChange,getConfig}){
  if(!anchor) return {open:()=>{},close:()=>{},destroy:()=>{}};
  const menu=document.createElement('div'); menu.className='volume-config-menu'; menu.hidden=true;
  menu.innerHTML='<div class="volume-config-head"><div><div class="volume-config-title">Configurar Volume</div><div class="volume-config-subtitle">Barras e média do volume</div></div><button type="button" class="volume-config-close" aria-label="Fechar configuração do volume" title="Fechar">×</button></div><div class="volume-config-section"><div class="volume-config-section-title">MÉDIA</div><label class="volume-config-field"><span>Mostrar média</span><input data-volume-average type="checkbox"></label><label class="volume-config-field"><span>Período</span><input data-volume-period type="number" min="2" max="200" step="1" inputmode="numeric"></label><label class="volume-config-field"><span>Tipo</span><select data-volume-type><option value="sma">SMA</option><option value="ema">EMA</option></select></label></div><div class="volume-config-section"><div class="volume-config-section-title">BARRAS</div><label class="volume-config-field"><span>Alta</span><input data-volume-up type="color"></label><label class="volume-config-field"><span>Baixa</span><input data-volume-down type="color"></label></div><div class="volume-config-section"><div class="volume-config-section-title">MÉDIA</div><label class="volume-config-field"><span>Cor</span><input data-volume-average-color type="color"></label></div><div class="volume-config-hint">Toque fora para fechar</div>';
  document.body.appendChild(menu);
  const fields={showAverage:menu.querySelector('[data-volume-average]'),averagePeriod:menu.querySelector('[data-volume-period]'),averageType:menu.querySelector('[data-volume-type]'),upColor:menu.querySelector('[data-volume-up]'),downColor:menu.querySelector('[data-volume-down]'),averageColor:menu.querySelector('[data-volume-average-color]')};
  const normalize=cfg=>({showAverage:cfg?.showAverage!==false,averagePeriod:Math.max(2,Math.min(200,Math.floor(Number(cfg?.averagePeriod)||20))),averageType:cfg?.averageType==='ema'?'ema':'sma',upColor:cfg?.upColor||'#4ade80',downColor:cfg?.downColor||'#f87171',averageColor:cfg?.averageColor||'#f59e0b'});
  const sync=cfg=>{const c=normalize(cfg);fields.showAverage.checked=c.showAverage;fields.averagePeriod.value=c.averagePeriod;fields.averageType.value=c.averageType;fields.upColor.value=c.upColor;fields.downColor.value=c.downColor;fields.averageColor.value=c.averageColor;};
  const emit=()=>onChange?.(normalize({showAverage:fields.showAverage.checked,averagePeriod:fields.averagePeriod.value,averageType:fields.averageType.value,upColor:fields.upColor.value,downColor:fields.downColor.value,averageColor:fields.averageColor.value}));
  const position=()=>{const r=anchor.getBoundingClientRect(),w=Math.min(270,innerWidth-16),left=Math.max(8,Math.min(r.left,innerWidth-w-8));menu.style.width=w+'px';menu.style.left=left+'px';menu.style.top=Math.min(r.bottom+8,innerHeight-menu.offsetHeight-8)+'px';};
  const open=cfg=>{sync(cfg||getConfig?.()||{});menu.hidden=false;requestAnimationFrame(position);};
  const close=()=>{menu.hidden=true;};
  const onDocumentPointerDown=e=>{if(menu.hidden||e.target===anchor||menu.contains(e.target))return;close();};
  menu.addEventListener('change',emit); menu.addEventListener('input',emit); menu.querySelector('.volume-config-close').addEventListener('click',close);
  const onKeyDown=e=>{if(e.key==='Escape'&&!menu.hidden)close();};
  document.addEventListener('keydown',onKeyDown); document.addEventListener('pointerdown',onDocumentPointerDown); window.addEventListener('resize',position); window.addEventListener('scroll',position,true);
  return {open,close,destroy:()=>{document.removeEventListener('keydown',onKeyDown);document.removeEventListener('pointerdown',onDocumentPointerDown);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);menu.remove();}};
}
