const P={left:10,right:58,top:10,bottom:24};
export function attachChartInteraction({canvas,viewport,draw}){
  const pointers=new Map();let drag=null,pinch=null;
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
  function down(e){if(e.pointerType==="mouse"&&e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,point(e));try{canvas.setPointerCapture(e.pointerId)}catch{};if(pointers.size===1){drag={...point(e)};pinch=null;canvas.style.cursor="grabbing"}else if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}};drag=null}}
  function move(e){if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,point(e));const r=canvas.getBoundingClientRect();if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},distance=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),prev=pinch.distance;if(Math.abs(distance-prev)>2){const f=Math.max(.94,Math.min(1.06,prev/distance)),w=Math.max(1,r.width-P.left-P.right),h=Math.max(1,r.height-P.top-P.bottom),xr=Math.max(0,Math.min(1,(center.x-P.left)/w)),yr=Math.max(0,Math.min(1,(center.y-P.top)/h)),s=viewport.getState();viewport.zoomX(f,s.x.min+(s.x.max-s.x.min)*xr);viewport.zoomY(f,viewport.priceAtYRatio(yr));pinch.distance=distance}else{const dx=center.x-pinch.center.x,dy=center.y-pinch.center.y,s=viewport.getState(),w=Math.max(1,r.width-P.left-P.right);viewport.panX(-(dx/w)*(s.x.max-s.x.min));viewport.panYByPixels(dy,Math.max(1,r.height-P.top-P.bottom))}pinch.center=center;draw();return}if(!drag)return;const p=point(e),dx=p.x-drag.x,dy=p.y-drag.y,s=viewport.getState(),w=Math.max(1,r.width-P.left-P.right),h=Math.max(1,r.height-P.top-P.bottom);if(Math.abs(dx)>=1)viewport.panX(-(dx/w)*(s.x.max-s.x.min));if(Math.abs(dy)>=1)viewport.panYByPixels(dy,h);drag=p;draw()}
  function up(e){pointers.delete(e.pointerId);try{canvas.releasePointerCapture(e.pointerId)}catch{};if(!pointers.size){drag=null;pinch=null;canvas.style.cursor="grab"}}
  function wheel(e){e.preventDefault();const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width-P.left-P.right),ratio=Math.max(0,Math.min(1,(e.clientX-r.left-P.left)/w)),s=viewport.getState();viewport.zoomX(e.deltaY>0?1.12:.89,s.x.min+(s.x.max-s.x.min)*ratio);draw()}
  canvas.addEventListener("pointerdown",down,{passive:false});canvas.addEventListener("pointermove",move,{passive:false});canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("wheel",wheel,{passive:false});canvas.style.touchAction="none";
  return()=>{canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel)}
}