const P={left:10,right:58,top:10,bottom:24};
export function attachChartInteraction({canvas,viewport,draw,onViewportChanged=()=>{}}){
 const pointers=new Map();let owner=null;let gesture={type:null,last:null,pinchDistance:null,pinchCenter:null,pinchVector:null};
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const priceScale=p=>p.x>=Math.max(0,canvas.clientWidth-P.right);
 const down=e=>{if(e.pointerType==="mouse"&&e.button!==0)return;e.preventDefault();const p=point(e);pointers.set(e.pointerId,p);try{canvas.setPointerCapture(e.pointerId)}catch{};if(pointers.size===1){owner="chart";gesture={type:priceScale(p)?"price-scale":null,last:p,pinchDistance:null,pinchCenter:null,pinchVector:null};canvas.style.cursor="grabbing"}else if(owner==="chart"){const[a,b]=[...pointers.values()];gesture.type="two-finger";gesture.pinchDistance=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));gesture.pinchCenter={x:(a.x+b.x)/2,y:(a.y+b.y)/2};gesture.pinchVector={x:b.x-a.x,y:b.y-a.y};gesture.last=null}};
 const move=e=>{if(!pointers.has(e.pointerId)||owner!=="chart")return;e.preventDefault();const p=point(e);pointers.set(e.pointerId,p);const r=canvas.getBoundingClientRect();
  if(pointers.size>=2){const[a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},prev=gesture.pinchDistance||Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),next=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),distanceChange=Math.abs(next-prev),centerChange=gesture.pinchCenter?Math.hypot(center.x-gesture.pinchCenter.x,center.y-gesture.pinchCenter.y):0,isPinch=distanceChange>Math.max(2,centerChange*1.35);
   if(isPinch){const factor=Math.max(.94,Math.min(1.06,Math.pow(prev/next,.42))),s=viewport.getState(),pw=Math.max(1,r.width-P.left-P.right),ph=Math.max(1,r.height-P.top-P.bottom),xr=Math.max(0,Math.min(1,(center.x-P.left)/pw)),yr=Math.max(0,Math.min(1,(center.y-P.top)/ph)),xa=s.x.min+(s.x.max-s.x.min)*xr,ya=viewport.priceAtYRatio(yr),v={x:b.x-a.x,y:b.y-a.y},pv=gesture.pinchVector||v,dx=Math.abs(v.x)-Math.abs(pv.x),dy=Math.abs(v.y)-Math.abs(pv.y),ax=Math.abs(dx),ay=Math.abs(dy),dominant=Math.max(ax,ay),diagonal=dominant>=1.5&&Math.min(ax,ay)>=dominant*.35,horizontal=!diagonal&&ax>=1.5&&ax>ay*1.35,vertical=!diagonal&&ay>=1.5&&ay>ax*1.35;
    if(horizontal){viewport.zoomX(factor,xa);gesture.type="pinch-x"}else if(vertical){if(Number.isFinite(ya))viewport.zoomY(factor,ya);gesture.type="pinch-y"}else if(diagonal){viewport.zoomX(factor,xa);if(Number.isFinite(ya))viewport.zoomY(factor,ya);gesture.type="pinch-xy"}
   }else{const last=gesture.pinchCenter||center,dx=center.x-last.x,dy=center.y-last.y,s=viewport.getState(),pw=Math.max(1,r.width-P.left-P.right),ph=Math.max(1,r.height-P.top-P.bottom);viewport.panX(-(dx/pw)*(s.x.max-s.x.min));viewport.panYByPixels(dy,ph);gesture.type="two-finger-pan"}
   gesture.pinchDistance=next;gesture.pinchCenter=center;gesture.pinchVector={x:b.x-a.x,y:b.y-a.y};draw();return}
  const last=gesture.last;if(!last){gesture.last=p;return}const dx=p.x-last.x,dy=p.y-last.y;
  if(gesture.type==="price-scale"){const ph=Math.max(1,r.height-P.top-P.bottom),ratio=Math.max(0,Math.min(1,(p.y-P.top)/ph)),anchor=viewport.priceAtYRatio(ratio);viewport.zoomY(Math.exp(-dy/220),anchor)}
  else if(!gesture.type&&(Math.abs(dx)>=6||Math.abs(dy)>=6)){const ax=Math.abs(dx),ay=Math.abs(dy),dominant=Math.max(ax,ay),diagonal=Math.min(ax,ay)>=dominant*.35;gesture.type=diagonal?"pan-xy":ax>=ay?"pan-x":"pan-y"}
  if(gesture.type==="pan-x"||gesture.type==="pan-xy"){const s=viewport.getState(),pw=Math.max(1,r.width-P.left-P.right);viewport.panX(-(dx/pw)*(s.x.max-s.x.min))}
  if(gesture.type==="pan-y"||gesture.type==="pan-xy"){const ph=Math.max(1,r.height-P.top-P.bottom);viewport.panYByPixels(dy,ph)}
  gesture.last=p;draw();
 };
 const up=e=>{if(!pointers.has(e.pointerId))return;pointers.delete(e.pointerId);try{canvas.releasePointerCapture(e.pointerId)}catch{};if(!pointers.size){const changed=owner==="chart"&&Boolean(gesture.type);owner=null;gesture={type:null,last:null,pinchDistance:null,pinchCenter:null,pinchVector:null};canvas.style.cursor="grab";if(changed)onViewportChanged()}else if(pointers.size===1&&owner==="chart"){gesture.type=null;gesture.last=[...pointers.values()][0];gesture.pinchDistance=null;gesture.pinchCenter=null;gesture.pinchVector=null}};
 const wheel=e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),pw=Math.max(1,r.width-P.left-P.right),ratio=Math.max(0,Math.min(1,(e.clientX-r.left-P.left)/pw)),s=viewport.getState(),anchor=s.x.min+(s.x.max-s.x.min)*ratio;viewport.zoomX(e.deltaY>0?1.12:.89,anchor);draw()};
 canvas.addEventListener("pointerdown",down,{passive:false});canvas.addEventListener("pointermove",move,{passive:false});canvas.addEventListener("pointerup",up,{passive:false});canvas.addEventListener("pointercancel",up,{passive:false});canvas.addEventListener("wheel",wheel,{passive:false});canvas.style.touchAction="none";canvas.style.cursor="grab";
 return()=>{canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel);canvas.style.touchAction="";canvas.style.cursor=""}
}