const P={left:10,right:58,top:10,bottom:24};
export function attachChartInteraction({canvas,viewport,draw,onViewportChanged=()=>{}}){
  const pointers=new Map();let drag=null,pinch=null;
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
  function down(e){if(e.pointerType==="mouse"&&e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,point(e));try{canvas.setPointerCapture(e.pointerId)}catch{};if(pointers.size===1){drag={...point(e)};pinch=null;canvas.style.cursor="grabbing"}else if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},spanX:Math.abs(b.x-a.x),spanY:Math.abs(b.y-a.y)};drag=null}}
  function move(e){if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,point(e));const r=canvas.getBoundingClientRect();if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2},spanX=Math.max(1,Math.abs(b.x-a.x)),spanY=Math.max(1,Math.abs(b.y-a.y)),deltaX=spanX-pinch.spanX,deltaY=spanY-pinch.spanY,s=viewport.getState(),w=Math.max(1,r.width-P.left-P.right),h=Math.max(1,r.height-P.top-P.bottom),xr=Math.max(0,Math.min(1,(center.x-P.left)/w)),yr=Math.max(0,Math.min(1,(center.y-P.top)/h));
      if(Math.abs(deltaX)>Math.abs(deltaY)&&Math.abs(deltaX)>1){const fX=Math.max(.9,Math.min(1.1,pinch.spanX/spanX));viewport.zoomX(fX,s.x.min+(s.x.max-s.x.min)*xr);pinch.spanX=spanX;pinch.spanY=spanY;}
      else if(Math.abs(deltaY)>1){const fY=Math.max(.9,Math.min(1.1,pinch.spanY/spanY));viewport.zoomY(fY,viewport.priceAtYRatio(yr));pinch.spanX=spanX;pinch.spanY=spanY;}
      else {pinch.spanX=spanX;pinch.spanY=spanY;}
      pinch.center=center;draw();onViewportChanged();return}if(!drag)return;const p=point(e),dx=p.x-drag.x,dy=p.y-drag.y,s=viewport.getState(),w=Math.max(1,r.width-P.left-P.right),h=Math.max(1,r.height-P.top-P.bottom),onYAxis=p.x>=r.width-P.right;if(onYAxis&&Math.abs(dy)>=1){const factor=Math.max(.97,Math.min(1.03,1-dy/Math.max(80,h)));viewport.zoomY(factor,viewport.priceAtYRatio(Math.max(0,Math.min(1,(p.y-P.top)/h))))}else{if(Math.abs(dx)>=1)viewport.panX(-(dx/w)*(s.x.max-s.x.min));if(Math.abs(dy)>=1)viewport.panYByPixels(dy,h)}drag=p;draw();onViewportChanged()}
  function up(e){pointers.delete(e.pointerId);try{canvas.releasePointerCapture(e.pointerId)}catch{};if(!pointers.size){drag=null;pinch=null;canvas.style.cursor="grab"}}
  function wheel(e){e.preventDefault();const r=canvas.getBoundingClientRect(),w=Math.max(1,r.width-P.left-P.right),ratio=Math.max(0,Math.min(1,(e.clientX-r.left-P.left)/w)),s=viewport.getState();viewport.zoomX(e.deltaY>0?1.12:.89,s.x.min+(s.x.max-s.x.min)*ratio);draw();onViewportChanged()}
  canvas.addEventListener("pointerdown",down,{passive:false});canvas.addEventListener("pointermove",move,{passive:false});canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("wheel",wheel,{passive:false});canvas.style.touchAction="none";
  return()=>{canvas.removeEventListener("pointerdown",down);canvas.removeEventListener("pointermove",move);canvas.removeEventListener("pointerup",up);canvas.removeEventListener("pointercancel",up);canvas.removeEventListener("wheel",wheel)}
}