/* ORACULUM — análise completa */
import {wireMetricHelp} from './metric-help.js';
export function openModal({focusAdvanced=false,result:r,metric,statBlock,pct,fmt,date}){
   if(!r)return;const modal=document.createElement('div');modal.className='analysis-modal';
   const rows=Object.values(r.series).map(s=>'<tr><td><b>'+s.symbol+'</b></td><td>'+pct(s.total)+'</td><td>'+pct(s.cagr)+'</td><td>'+pct(s.vol)+'</td><td>'+pct(s.drawdown)+'</td><td>'+fmt(s.sharpe,3)+'</td><td>'+pct(s.winRate)+'</td></tr>').join('');
   const advanced=Object.values(r.series).map(s=>statBlock(s.symbol+' · DISTRIBUIÇÃO E RISCO',[metric('Média',pct(s.mean),'por intervalo','Média dos log-retornos.'),metric('Mediana',pct(s.median),'por intervalo','Valor central dos retornos; reduz o efeito de extremos.'),metric('Melhor período',pct(s.best),'máximo','Maior retorno em uma observação.'),metric('Pior período',pct(s.worst),'mínimo','Menor retorno em uma observação.'),metric('ATL','$ '+fmt(s.atl),'mínimo','Menor preço observado.'),metric('ATH','$ '+fmt(s.ath),'máximo','Maior preço observado.')])).join('');
   const rel=r.relations.map(x=>statBlock(x.primary.toUpperCase()+' × '+x.target.toUpperCase(),[metric('Correlação',fmt(x.correlation,4),'retornos','Perto de +1 = juntos; perto de -1 = opostos.'),metric('Covariância',fmt(x.covariance,6),'retornos','Movimento conjunto em escala dependente dos ativos.'),metric('Beta',fmt(x.beta,4),'sensibilidade','Sensibilidade linear do alvo em relação à referência.'),metric('Alpha',fmt(x.alpha,6),'intercepto','Componente médio não explicado pelo beta no modelo simples.'),metric('R²',pct(x.r2),'ajuste linear','Quanto da variação do alvo é explicada pela referência.'),metric('Corr. móvel',fmt(x.rolling,4),'última janela','Correlação na janela móvel mais recente.'),metric('Lead/Lag',String(x.leadLag.lag),'intervalos','Defasagem com maior correlação absoluta entre -5 e +5.')])).join('');
   const model=r.explanatoryModel,diag=r.modelDiagnostics;
   const modelSection=model?.available?'<section><h3>EXPLICAÇÃO MULTIVARIADA · '+model.target+'</h3><div class="analysis-explain"><b>Pergunta investigada:</b> as variáveis selecionadas ajudam a explicar os retornos de '+model.target+'?<br>O modelo estima a associação conjunta entre os retornos selecionados e o retorno da referência. <b>R²</b> mostra a parcela da variação observada no alvo associada ao ajuste; <b>R² ajustado</b> penaliza complexidade. Isso não demonstra causalidade.</div><table><thead><tr><th>Variável</th><th>Coeficiente β</th><th>Erro-padrão</th><th>t</th><th>p aprox.</th></tr></thead><tbody>'+model.coefficients.map(c=>'<tr><td><b>'+c.name+'</b></td><td>'+fmt(c.beta,5)+'</td><td>'+fmt(c.se,5)+'</td><td>'+fmt(c.t,3)+'</td><td>'+fmt(c.p,4)+'</td></tr>').join('')+'</tbody></table><div class="results-grid">'+metric('R²',pct(model.r2),'explicação conjunta','Parcela da variação dos retornos do alvo associada ao modelo linear.')+metric('R² ajustado',pct(model.adjustedR2),'complexidade penalizada','Versão que penaliza a inclusão de variáveis que não acrescentam explicação suficiente.')+metric('Observações',fmt(model.observations,0),'retornos usados','Número de observações efetivamente estimadas no modelo.')+metric('Variáveis',fmt(model.predictors.length,0),'preditoras','Quantidade de variáveis selecionadas além da referência.')+'</div>'+(diag?.available?'<div class="analysis-explain"><b>Diagnóstico dos resíduos:</b> média '+fmt(diag.residualMean,6)+' · desvio-padrão '+fmt(diag.residualStd,6)+' · Durbin-Watson '+fmt(diag.durbinWatson,3)+' · razão de variâncias '+fmt(diag.varianceRatio,3)+'. Esses indicadores são diagnósticos iniciais; não substituem testes econométricos formais.</div>':'')+'</section>':'<section><h3>EXPLICAÇÃO MULTIVARIADA</h3><div class="analysis-explain"><b>Modelo não estimado.</b> '+(model?.reason||'Selecione variáveis além da referência.')+'</div></section>';
   modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-modal-panel" role="dialog" aria-modal="true"><header><div><strong>ANÁLISE COMPLETA</strong><small>'+r.observations+' observações · '+r.interval+' · '+date(r.rowsStart)+' → '+date(r.rowsEnd)+'</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-modal-body"><section><h3>O QUE FOI ANALISADO</h3><div class="analysis-explain"><b>Referência:</b> '+r.series[Object.keys(r.series)[0]].symbol+' · <b>Janela:</b> '+date(r.rowsStart)+' → '+date(r.rowsEnd)+' · <b>Observações:</b> '+r.observations+' · <b>Intervalo:</b> '+r.interval+'.<br>Os timestamps foram alinhados antes dos cálculos. Retornos usam log-retornos; volatilidade, Sharpe e Sortino são anualizados conforme o intervalo.</div></section><section><h3>PERFORMANCE E RISCO</h3><table><thead><tr><th>Ativo</th><th>Retorno</th><th>CAGR</th><th>Vol.</th><th>DD</th><th>Sharpe</th><th>Win rate</th></tr></thead><tbody>'+rows+'</tbody></table></section><section><h3>ESTATÍSTICAS AVANÇADAS</h3>'+advanced+'</section><section><h3>RELAÇÕES ESTATÍSTICAS</h3>'+rel+'</section>'+modelSection+'<section><h3>INTERPRETAÇÃO</h3><div class="analysis-explain"><p><b>Correlação não é causalidade.</b> Mede associação estatística entre retornos.</p><p><b>Beta</b> mede sensibilidade relativa. <b>R²</b> mede o quanto o modelo linear simples explica da variação do alvo.</p><p><b>Lead/Lag</b> procura defasagens de até 5 intervalos. É diagnóstico exploratório, não prova de previsão.</p><p><b>Base 100 + log</b> permite comparar trajetórias com preços absolutos muito diferentes.</p></div></section></div></section>';
   const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);wireMetricHelp(modal);if(focusAdvanced)modal.querySelector('.analysis-stat-block')?.scrollIntoView();
 }
