/* ORACULUM — análise completa */
import {wireMetricHelp} from './metric-help.js';
function correlationMatrix(series){const items=series.map(s=>({key:s.key,symbol:s.symbol,returns:s.returns||[]}));const corr=(a,b)=>{const n=Math.min(a.length,b.length);if(n<2)return NaN;const x=a.slice(-n),y=b.slice(-n),mx=x.reduce((s,v)=>s+v,0)/n,my=y.reduce((s,v)=>s+v,0)/n;let xy=0,xx=0,yy=0;for(let i=0;i<n;i++){const dx=x[i]-mx,dy=y[i]-my;xy+=dx*dy;xx+=dx*dx;yy+=dy*dy}return xx&&yy?xy/Math.sqrt(xx*yy):NaN};return items.map((row,i)=>({...row,values:items.map((col,j)=>i===j?1:corr(row.returns,col.returns))}));}
function corrClass(v){if(!Number.isFinite(v))return 'corr-na';if(v>=.7)return 'corr-strong-pos';if(v>=.3)return 'corr-pos';if(v>-0.3)return 'corr-neutral';if(v>-0.7)return 'corr-neg';return 'corr-strong-neg'}

export function openModal({focusAdvanced=false,result:r,metric,statBlock,pct,fmt,date}){
   if(!r)return;const modal=document.createElement('div');modal.className='analysis-modal';
   const rows=Object.values(r.series).map(s=>'<tr><td><b>'+s.symbol+'</b></td><td>'+pct(s.total)+'</td><td>'+pct(s.cagr)+'</td><td>'+pct(s.vol)+'</td><td>'+pct(s.drawdown)+'</td><td>'+fmt(s.sharpe,3)+'</td><td>'+pct(s.winRate)+'</td></tr>').join('');
   const advanced=Object.values(r.series).map(s=>statBlock(s.symbol+' · DISTRIBUIÇÃO E RISCO',[metric('Média',pct(s.mean),'por intervalo','Média dos log-retornos.'),metric('Mediana',pct(s.median),'por intervalo','Valor central dos retornos; reduz o efeito de extremos.'),metric('Melhor período',pct(s.best),'máximo','Maior retorno em uma observação.'),metric('Pior período',pct(s.worst),'mínimo','Menor retorno em uma observação.'),metric('Assimetria',fmt(s.skewness,3),'distribuição','Assimetria amostral dos retornos.'),metric('Curtose excedente',fmt(s.excessKurtosis,3),'caudas','Curtose amostral menos 3.'),metric('VaR 95%',pct(s.var95),'perda histórica','Perda diária/por intervalo no quantil de 5%.'),metric('ES 95%',pct(s.es95),'cauda','Perda média além do VaR 95%.'),metric('VaR 99%',pct(s.var99),'cauda extrema','Quantil histórico de 1%.'),metric('ES 99%',pct(s.es99),'cauda extrema','Perda média além do VaR 99%.'),metric('Calmar',fmt(s.calmar,3),'retorno / drawdown','CAGR dividido pelo drawdown máximo absoluto.'),metric('ATL','$ '+fmt(s.atl),'mínimo','Menor preço observado.'),metric('ATH','$ '+fmt(s.ath),'máximo','Maior preço observado.')])).join('');
   const matrix=correlationMatrix(Object.values(r.series));
   const matrixSection=matrix.length>1?'<section><h3>MATRIZ DE CORRELAÇÃO · RETORNOS</h3><div class="analysis-explain"><b>Como ler:</b> cada célula mostra a correlação de Pearson entre o par. A intensidade indica a força da associação linear; azul é positiva e vermelho negativa. A diagonal é 1.</div><div class="correlation-matrix-wrap"><table class="correlation-matrix"><thead><tr><th></th>'+matrix.map(x=>'<th>'+x.symbol+'</th>').join('')+'</tr></thead><tbody>'+matrix.map(row=>'<tr><th>'+row.symbol+'</th>'+row.values.map(v=>'<td class="'+corrClass(v)+'">'+fmt(v,2)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><div class="corr-legend"><span><i class="corr-swatch corr-strong-pos"></i> forte positiva</span><span><i class="corr-swatch corr-pos"></i> positiva</span><span><i class="corr-swatch corr-neutral"></i> próxima de zero</span><span><i class="corr-swatch corr-neg"></i> negativa</span><span><i class="corr-swatch corr-strong-neg"></i> forte negativa</span></div></section>':'';
   const rel=r.relations.map(x=>statBlock(x.primary.toUpperCase()+' × '+x.target.toUpperCase(),[metric('Correlação',fmt(x.correlation,4),'retornos','Perto de +1 = juntos; perto de -1 = opostos.'),metric('Covariância',fmt(x.covariance,6),'retornos','Movimento conjunto em escala dependente dos ativos.'),metric('Beta',fmt(x.beta,4),'sensibilidade','Sensibilidade linear do alvo em relação à referência.'),metric('Alpha',fmt(x.alpha,6),'intercepto','Componente médio não explicado pelo beta no modelo simples.'),metric('R²',pct(x.r2),'ajuste linear','Quanto da variação do alvo é explicada pela referência.'),metric('Corr. móvel',fmt(x.rolling,4),'última janela','Correlação na janela móvel mais recente.'),metric('Lead/Lag',String(x.leadLag.lag),'intervalos','Defasagem com maior correlação absoluta entre -5 e +5.')])).join('');
   const model=r.explanatoryModel,diag=r.modelDiagnostics;
   const modelSection=model?.available?'<section><h3>EXPLICAÇÃO MULTIVARIADA · '+model.target+'</h3><div class="analysis-explain"><b>Pergunta investigada:</b> as variáveis selecionadas ajudam a explicar os retornos de '+model.target+'?<br>O modelo estima a associação conjunta entre os retornos selecionados e o retorno da referência. <b>R²</b> mostra a parcela da variação observada no alvo associada ao ajuste; <b>R² ajustado</b> penaliza complexidade. Isso não demonstra causalidade.</div><table><thead><tr><th>Variável</th><th>Coeficiente β</th><th>Erro-padrão</th><th>t</th><th>p</th><th>IC 95%</th><th>HAC SE</th><th>HAC p</th></tr></thead><tbody>'+model.coefficients.map(c=>'<tr><td><b>'+c.name+'</b></td><td>'+fmt(c.beta,5)+'</td><td>'+fmt(c.se,5)+'</td><td>'+fmt(c.t,3)+'</td><td>'+fmt(c.p,4)+'</td></tr>').join('')+'</tbody></table><div class="results-grid">'+metric('R²',pct(model.r2),'explicação conjunta','Parcela da variação dos retornos do alvo associada ao modelo linear.')+metric('R² ajustado',pct(model.adjustedR2),'complexidade penalizada','Versão que penaliza a inclusão de variáveis que não acrescentam explicação suficiente.')+metric('Observações',fmt(model.observations,0),'retornos usados','Número de observações efetivamente estimadas no modelo.')+metric('Variáveis',fmt(model.predictors.length,0),'preditoras','Quantidade de variáveis selecionadas além da referência.')+metric('F',fmt(model.f,3),'teste conjunto','Teste de significância conjunta das preditoras.')+metric('p do F',fmt(model.fP,5),'teste conjunto','P-valor do teste F global.')+metric('RMSE',fmt(model.rmse,6),'resíduo','Raiz do erro quadrático médio.')+metric('HAC lag',fmt(model.hacLag,0),'Newey-West','Número de defasagens usado na covariância robusta.')+(model.vif?.length?model.vif.map((v,i)=>metric('VIF · '+model.predictors[i],fmt(v.vif,2),'colinearidade','VIF = 1/(1 − R² da variável contra as demais).')).join(''):'')+'</div>'+(diag?.available?'<div class="analysis-explain"><b>Diagnóstico dos resíduos:</b> média '+fmt(diag.residualMean,6)+' · desvio-padrão '+fmt(diag.residualStd,6)+' · Durbin-Watson '+fmt(diag.durbinWatson,3)+' · Ljung-Box p '+fmt(diag.ljungBox?.p,4)+' · razão de variâncias '+fmt(diag.varianceRatio,3)+'. O Ljung-Box testa autocorrelação conjunta nas defasagens usadas; estes diagnósticos não provam causalidade.</div>':'')+'</section>':'<section><h3>EXPLICAÇÃO MULTIVARIADA</h3><div class="analysis-explain"><b>Modelo não estimado.</b> '+(model?.reason||'Selecione variáveis além da referência.')+'</div></section>';
   modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-modal-panel" role="dialog" aria-modal="true"><header><div><strong>ANÁLISE COMPLETA</strong><small>'+r.observations+' observações · '+r.interval+' · '+date(r.rowsStart)+' → '+date(r.rowsEnd)+'</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-modal-body"><section><h3>O QUE FOI ANALISADO</h3><div class="analysis-explain"><b>Referência:</b> '+r.series[Object.keys(r.series)[0]].symbol+' · <b>Janela:</b> '+date(r.rowsStart)+' → '+date(r.rowsEnd)+' · <b>Observações:</b> '+r.observations+' · <b>Intervalo:</b> '+r.interval+'.<br>Os timestamps foram alinhados antes dos cálculos. Retornos usam log-retornos; volatilidade, Sharpe e Sortino são anualizados conforme o intervalo.</div></section><section><h3>PERFORMANCE E RISCO</h3><table><thead><tr><th>Ativo</th><th>Retorno</th><th>CAGR</th><th>Vol.</th><th>DD</th><th>Sharpe</th><th>Win rate</th></tr></thead><tbody>'+rows+'</tbody></table></section><section><h3>ESTATÍSTICAS AVANÇADAS</h3>'+advanced+'</section>'+matrixSection+'<section><h3>RELAÇÕES ESTATÍSTICAS</h3>'+rel+'</section>'+modelSection+'<section><h3>INTERPRETAÇÃO</h3><div class="analysis-explain"><p><b>Correlação não é causalidade.</b> Mede associação estatística entre retornos.</p><p><b>Beta</b> mede sensibilidade relativa. <b>R²</b> mede o quanto o modelo linear simples explica da variação do alvo.</p><p><b>Lead/Lag</b> procura defasagens de até 5 intervalos. É diagnóstico exploratório, não prova de previsão.</p><p><b>Base 100 + log</b> permite comparar trajetórias com preços absolutos muito diferentes.</p></div></section></div></section>';
   const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);wireMetricHelp(modal);if(focusAdvanced)modal.querySelector('.analysis-stat-block')?.scrollIntoView();
 }
