/* ORACULUM — análise investigativa sob demanda */
import {analyzeSeries,alignSeries} from './engine.js';

function fmt(v,d=2){if(!Number.isFinite(v))return '—';return new Intl.NumberFormat('pt-BR',{maximumFractionDigits:d}).format(v)}
function pct(v,d=2){return Number.isFinite(v)?fmt(v*100,d)+'%':'—'}
function date(v){return Number.isFinite(Number(v))?new Date(Number(v)).toLocaleDateString('pt-BR'):'—'}
function metric(label,value,note='',help=''){return '<div class="analysis-metric"><div class="metric-label"><span>'+label+'</span><button class="metric-help" type="button" data-topic="'+label.replace(/"/g,'&quot;')+'" aria-label="Explicar '+label+'">?</button></div><strong>'+value+'</strong>'+(note?'<small>'+note+'</small>':'')+'</div>'}
function statBlock(title,items){return '<section class="analysis-stat-block"><h3>'+title+'</h3><div class="results-grid">'+items.join('')+'</div></section>'}

export function attachComparisonAnalysis({dataClient,normalizeCandles,getCandles,getInterval,getActiveSymbol,assets}){
 const $=s=>document.querySelector(s),state={rows:null,result:null,selected:[],markers:{start:0,base:0,end:0}};
 const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
 const markerDate=(rows,i)=>rows[i]?date(rows[i].timestamp):'—';
 const renderMarkerTimeline=()=>{
   const host=$('#comparison-timeline');if(!host||!state.rows?.length)return;
   const max=Math.max(1,state.rows.length-1),m=state.markers;
   const make=(key,label,cls)=>'<button class="cmp-marker '+cls+'" data-marker="'+key+'" style="left:'+((m[key]/max)*100)+'%" aria-label="'+label+' '+markerDate(state.rows,m[key])+'"><span>'+label+'</span><b>'+markerDate(state.rows,m[key])+'</b></button>';
   host.innerHTML='<div class="cmp-timeline-track"></div>'+make('start','INÍCIO','marker-start')+make('base','BASE 100','marker-base')+make('end','FIM','marker-end');
   host.querySelectorAll('.cmp-marker').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();const key=btn.dataset.marker;btn.setPointerCapture?.(e.pointerId);const move=ev=>{const rect=host.getBoundingClientRect(),x=clamp(ev.clientX-rect.left,0,rect.width),idx=Math.round((x/rect.width)*max);const min=key==='base'?m.start:key==='end'?m.base:0,maxAllowed=key==='start'?m.base:key==='base'?m.end:max;m[key]=clamp(idx,min,maxAllowed);renderMarkerTimeline();renderChart(state.rows,state.selected.map(k=>({...assets[k],key:k})).filter(Boolean));const fresh=document.querySelector('#comparison-timeline .cmp-marker[data-marker="'+key+'"]');fresh?.setPointerCapture?.(ev.pointerId)};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)})});
 };
 const renderChart=(rows,series)=>{
   const host=$('#comparison-chart');if(!host||!rows.length)return;
   const w=Math.max(320,host.clientWidth||800),h=280,p={l:48,r:18,t:18,b:32};
   const start=state.markers.start,base=state.markers.base,end=state.markers.end,view=rows.slice(start,end+1),baseRow=rows[base]||view[0];
   const normalized=series.map(s=>view.map(r=>100*r[s.key]/baseRow[s.key]));
   const all=normalized.flat(),lo=Math.log(Math.min(...all)),hi=Math.log(Math.max(...all));
   const t0=view[0]?.timestamp??0,t1=view.at(-1)?.timestamp??t0,span=Math.max(1,t1-t0);
   const line=vals=>vals.map((v,i)=>{const ts=view[i]?.timestamp??t0,x=p.l+((ts-t0)/span)*(w-p.l-p.r),y=h-p.b-(Math.log(Math.max(.0001,v))-lo)/(hi-lo||1)*(h-p.t-p.b);return x.toFixed(2)+','+y.toFixed(2)}).join(' ');
   const polylines=normalized.map((v,i)=>'<polyline points="'+line(v)+'" class="cmp-line cmp-'+i+'"/>').join('');
   host.innerHTML='<svg viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none" role="img" aria-label="Comparação em base 100 e escala logarítmica"><line x1="'+p.l+'" x2="'+p.l+'" y1="'+p.t+'" y2="'+(h-p.b)+'" class="cmp-axis"/><line x1="'+p.l+'" x2="'+(w-p.r)+'" y1="'+(h-p.b)+'" y2="'+(h-p.b)+'" class="cmp-axis"/><line x1="'+p.l+'" x2="'+(w-p.r)+'" y1="'+(h/2)+'" y2="'+(h/2)+'" class="cmp-grid"/>'+polylines+'<text x="'+p.l+'" y="'+(h-8)+'">'+date(view[0].timestamp)+'</text><text x="'+(w-p.r)+'" y="'+(h-8)+'" text-anchor="end">'+date(view.at(-1).timestamp)+'</text><text x="'+(p.l+6)+'" y="'+(h/2-6)+'">100 = '+date(baseRow.timestamp)+'</text></svg>';
   const legend=$('#comparison-legend');if(legend)legend.innerHTML=series.map((s,i)=>'<span><i class="legend-'+i+'"></i>'+s.symbol+'</span>').join('');
 };
 const renderContext=(result,series)=>{
   const primary=series[0],targets=series.slice(1).map(s=>s.symbol).join(' + ')||'nenhum alvo selecionado';
   $('#analysis-context').innerHTML='<div class="context-row"><div><span>REFERÊNCIA</span><strong>'+primary.symbol+'</strong></div><div><span>COMPARANDO COM</span><strong>'+targets+'</strong></div><div><span>PERÍODO</span><strong>'+date(result.rowsStart)+' → '+date(result.rowsEnd)+'</strong></div><div><span>INTERVALO</span><strong>'+result.interval+'</strong></div><div><span>OBSERVAÇÕES</span><strong>'+result.observations+'</strong></div></div><div class="context-method"><div><b>DESENHO DA INVESTIGAÇÃO</b><span>Dados alinhados por timestamp · retornos conforme a configuração · janela móvel conforme especificação · resultados condicionados à amostra selecionada.</span></div><button id="show-data-table" type="button">VER DADOS UTILIZADOS ↗</button><button id="show-method" type="button">MÉTODO ?</button></div><div class="context-note"><b>Como ler:</b> a referência foi escolhida na configuração da investigação. Todas as séries foram alinhadas pelos mesmos timestamps antes dos cálculos. O índice é calculado como <b>100 × P(t) / P(base)</b>. Por padrão, BASE 100 começa na primeira observação comum às séries. A escala vertical é logarítmica; o eixo horizontal respeita o tempo real dos timestamps.</div>';
   $('#analysis-context').classList.remove('is-hidden');
 };
 const render=(result,series)=>{
   state.result=result;state.selected=series.map(x=>x.key);$('#comparison-panel').classList.remove('is-hidden');$('#analysis-status').textContent='CONCLUÍDA';
   $('#comparison-period').textContent=date(result.rowsStart)+' → '+date(result.rowsEnd)+' · '+result.observations+' observações';
   renderContext(result,series);renderChart(state.rows,series);renderMarkerTimeline();
   const primary=result.series[series[0].key],relations=result.relations;
   let html='<div class="analysis-section-label">RESULTADOS PRINCIPAIS · '+primary.symbol+' COMO REFERÊNCIA</div><div class="results-grid">'+metric('Retorno',pct(primary.total),'no período','Variação acumulada entre o primeiro e o último valor.')+metric('CAGR',pct(primary.cagr),'anualizado','Taxa composta anual equivalente ao período analisado.')+metric('Volatilidade',pct(primary.vol),'anualizada','Dispersão anualizada dos log-retornos.')+metric('Drawdown máximo',pct(primary.drawdown),'queda máxima','Maior perda de um pico até um vale no período.')+metric('Sharpe',fmt(primary.sharpe,3),'risco/retorno','Retorno médio ajustado pela volatilidade.')+metric('Sortino',fmt(primary.sortino,3),'risco de queda','Similar ao Sharpe, mas considera a dispersão negativa.')+metric('Win rate',pct(primary.winRate),'observações positivas','Percentual de períodos com retorno positivo.')+metric('ATH','$ '+fmt(primary.ath),'máxima observada','Maior preço observado na janela.')+'</div>';
   if(relations.length)html+='<div class="analysis-section-label">RELAÇÕES · REFERÊNCIA × ALVO</div><div class="results-grid">'+relations.map(r=>metric(r.target.toUpperCase()+' · CORR.',fmt(r.correlation,3),'associação','Correlação dos retornos; não implica causalidade.')+metric(r.target.toUpperCase()+' · BETA',fmt(r.beta,3),'sensibilidade','Sensibilidade do alvo em relação à referência.')+metric(r.target.toUpperCase()+' · R²',pct(r.r2),'ajuste linear','Parcela da variação do alvo explicada pelo modelo linear.')+metric(r.target.toUpperCase()+' · LEAD/LAG',String(r.leadLag.lag),'intervalos','Defasagem com maior correlação absoluta testada.')).join('')+'</div>';
   html+='<div class="analysis-section-label">AVANÇADO</div><div class="advanced-teaser"><span>Mediana, melhor/pior período, covariância, alpha, correlação móvel e diagnóstico de lead/lag.</span><button id="advanced-analysis">VER ESTATÍSTICAS AVANÇADAS ↗</button></div>';
   $('#analysis-results').innerHTML=html;$('#analysis-results').classList.remove('is-hidden');$('#full-analysis').classList.remove('is-hidden');$('#advanced-analysis').onclick=()=>openModal(true);wireHelp();document.querySelector('#show-data-table')?.addEventListener('click',openDataTable);document.querySelector('#show-method')?.addEventListener('click',()=>openInfo('MÉTODO'));
 };


 const topicText={
   'Retorno':{title:'Retorno',what:'Variação do preço entre observações consecutivas ou ao longo da janela selecionada.',formula:'r_t = \ln\left(\frac{P_t}{P_{t-1}}\right)',interpret:'No modo logarítmico, retornos são aditivos ao longo do tempo e aproximam a variação percentual para movimentos pequenos.',limits:'O resultado depende da frequência, da série de preços utilizada e do tratamento de observações ausentes.'},
   'CAGR':{title:'CAGR',what:'Taxa composta anualizada que representa o crescimento equivalente ao longo do período.',formula:'\mathrm{CAGR}=\left(\frac{P_f}{P_i}\right)^{1/T}-1',interpret:'É uma taxa anual equivalente; não significa que o ativo tenha crescido de forma uniforme.',limits:'Pode ser pouco representativo em períodos curtos ou em séries muito voláteis.'},
   'Volatilidade':{title:'Volatilidade',what:'Medida da dispersão dos retornos. No Oraculum, é anualizada conforme a frequência da série.',formula:'\sigma=\sqrt{\operatorname{Var}(r)}',interpret:'Maior volatilidade significa maior dispersão dos retornos, não necessariamente maior retorno esperado.',limits:'Volatilidade histórica não é uma previsão garantida da volatilidade futura.'},
   'Drawdown máximo':{title:'Drawdown máximo',what:'Maior queda observada de um pico até o vale subsequente.',formula:'DD_t=\frac{P_t}{\max_{u\le t}(P_u)}-1',interpret:'Quantifica a pior perda relativa a partir de um máximo histórico da janela.',limits:'Não descreve sozinho a duração da recuperação nem a frequência dos drawdowns.'},
   'Sharpe':{title:'Índice de Sharpe',what:'Relaciona retorno médio ao risco medido pela volatilidade.',formula:'\mathrm{Sharpe}=\frac{E[r]-r_f}{\sigma}',interpret:'No Oraculum, a interpretação é condicionada à convenção de risco/retorno usada pela implementação e à série escolhida.',limits:'A interpretação depende das hipóteses sobre distribuição, taxa livre de risco e período de estimação.'},
   'Sortino':{title:'Índice de Sortino',what:'Mede retorno ajustado pelo risco de queda, penalizando principalmente retornos abaixo do alvo.',formula:'\mathrm{Sortino}=\frac{E[r]-\tau}{\sigma_{\mathrm{downside}}}',interpret:'É útil quando o foco é distinguir volatilidade desejável de risco negativo.',limits:'Resultado sensível ao alvo e à definição de downside utilizada.'},
   'Win rate':{title:'Win rate',what:'Proporção de observações com retorno positivo.',formula:'\mathrm{Win\ rate}=\frac{N(r_t>0)}{N}',interpret:'Indica a frequência de períodos positivos, mas não o tamanho dos ganhos ou perdas.',limits:'Um win rate alto pode coexistir com perdas médias grandes.'},
   'ATH':{title:'ATH / ATL',what:'Maior ou menor preço observado dentro da amostra analisada.',formula:'\mathrm{ATH}=\max_t(P_t)\qquad;\qquad\mathrm{ATL}=\min_t(P_t)',interpret:'São estatísticas descritivas da janela, não estimativas de valor fundamental.',limits:'Mudar o período altera diretamente o máximo e o mínimo observados.'},
   'CORR.':{title:'Correlação de Pearson',what:'Mede a associação linear entre duas séries de retornos.',formula:'\rho=\frac{\operatorname{Cov}(X,Y)}{\sigma_X\sigma_Y}',interpret:'Valores próximos de +1 indicam associação linear positiva; próximos de −1, negativa; próximo de 0, pouca associação linear.',limits:'Correlação não implica causalidade e pode variar substancialmente ao longo do tempo.'},
   'BETA':{title:'Beta',what:'Mede a sensibilidade linear do retorno do ativo-alvo ao retorno da referência.',formula:'\beta=\frac{\operatorname{Cov}(R_X,R_M)}{\operatorname{Var}(R_M)}',interpret:'β > 1 indica maior sensibilidade que a referência; 0 < β < 1 indica menor sensibilidade.',limits:'É uma relação estatística dependente da amostra e da especificação; não é uma constante estrutural garantida.'},
   'R²':{title:'R²',what:'Mede a parcela da variação do alvo associada ao ajuste linear com a referência.',formula:'R^2=1-\frac{\mathrm{SSE}}{\mathrm{SST}}',interpret:'Em uma regressão linear simples com intercepto, R² está relacionado ao quadrado da correlação.',limits:'Não mede causalidade nem garante validade fora da amostra.'},
   'LEAD/LAG':{title:'Lead/Lag',what:'Procura uma defasagem temporal na qual a associação entre as séries seja maior em valor absoluto.',formula:'\rho_k=\operatorname{Corr}(X_t,Y_{t+k})',interpret:'É um diagnóstico exploratório de temporalidade estatística.',limits:'Não constitui evidência de causalidade nem de poder preditivo.'},
   'MÉTODO':{title:'Método e desenho da investigação',what:'A análise deve ser lida como uma sequência reproduzível: dados → tratamento → transformação → estimação → diagnóstico → interpretação.',formula:'Dados → Alinhamento → Retornos → Estatística/Modelo → Diagnóstico → Robustez',interpret:'O mesmo conjunto de dados pode produzir resultados diferentes quando mudamos período, frequência, transformação ou especificação. Por isso esses parâmetros são parte do resultado.',limits:'Nenhum resultado estatístico elimina as limitações da amostra ou transforma associação em causalidade.'}
 };
 function topicFor(label){const u=String(label).toUpperCase();if(u==='MÉTODO')return topicText['MÉTODO'];for(const k of Object.keys(topicText)){if(u.includes(k.toUpperCase()))return topicText[k]}return {title:label,what:'Estatística calculada a partir da amostra selecionada.',formula:'Consulte a especificação metodológica desta análise.',interpret:'O valor deve ser interpretado em conjunto com a amostra, período e método.',limits:'Resultados estatísticos são condicionados à especificação e aos dados utilizados.'}}
 function openInfo(label){
   const t=topicFor(label),modal=document.createElement('div');modal.className='analysis-info-modal';
   modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-info-panel" role="dialog" aria-modal="true"><header><div><strong>'+t.title+'</strong><small>EXPLICAÇÃO CIENTÍFICA</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-info-body"><section><h3>O QUE É</h3><p>'+t.what+'</p></section><section><h3>FORMULAÇÃO MATEMÁTICA</h3><div class="formula-box">\\['+t.formula+'\\]</div></section><section><h3>INTERPRETAÇÃO</h3><p>'+t.interpret+'</p></section><section><h3>LIMITAÇÕES</h3><p>'+t.limits+'</p></section></div></section>';
   const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([modal]);
 }
 function wireHelp(){document.querySelectorAll('.metric-help').forEach(b=>b.onclick=()=>openInfo(b.dataset.topic))}
 function openDataTable(){
   const rows=state.rows||[],keys=state.selected||[],modal=document.createElement('div');modal.className='analysis-info-modal';
   const headers=['DATA',...keys.map(k=>assets[k]?.symbol||k)];const body=rows.map(r=>'<tr><td>'+date(r.timestamp)+'</td>'+keys.map(k=>'<td>'+fmt(r[k],assets[k]?.symbol==='BTC'?2:4)+'</td>').join('')+'</tr>').join('');
   modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-info-panel data-table-panel" role="dialog" aria-modal="true"><header><div><strong>DADOS UTILIZADOS</strong><small>'+rows.length+' observações · '+date(rows[0]?.timestamp)+' → '+date(rows.at(-1)?.timestamp)+'</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-info-body"><p>Esta é a amostra efetivamente utilizada na comparação, após alinhamento pelos timestamps e aplicação do período selecionado. Valores são preços da série normalizada usada pelo estudo.</p><div class="data-table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table></div></div></section>';
   const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);
 }

 function openModal(focusAdvanced=false){
   const r=state.result;if(!r)return;const modal=document.createElement('div');modal.className='analysis-modal';
   const rows=Object.values(r.series).map(s=>'<tr><td><b>'+s.symbol+'</b></td><td>'+pct(s.total)+'</td><td>'+pct(s.cagr)+'</td><td>'+pct(s.vol)+'</td><td>'+pct(s.drawdown)+'</td><td>'+fmt(s.sharpe,3)+'</td><td>'+pct(s.winRate)+'</td></tr>').join('');
   const advanced=Object.values(r.series).map(s=>statBlock(s.symbol+' · DISTRIBUIÇÃO E RISCO',[metric('Média',pct(s.mean),'por intervalo','Média dos log-retornos.'),metric('Mediana',pct(s.median),'por intervalo','Valor central dos retornos; reduz o efeito de extremos.'),metric('Melhor período',pct(s.best),'máximo','Maior retorno em uma observação.'),metric('Pior período',pct(s.worst),'mínimo','Menor retorno em uma observação.'),metric('ATL','$ '+fmt(s.atl),'mínimo','Menor preço observado.'),metric('ATH','$ '+fmt(s.ath),'máximo','Maior preço observado.')])).join('');
   const rel=r.relations.map(x=>statBlock(x.primary.toUpperCase()+' × '+x.target.toUpperCase(),[metric('Correlação',fmt(x.correlation,4),'retornos','Perto de +1 = juntos; perto de -1 = opostos.'),metric('Covariância',fmt(x.covariance,6),'retornos','Movimento conjunto em escala dependente dos ativos.'),metric('Beta',fmt(x.beta,4),'sensibilidade','Sensibilidade linear do alvo em relação à referência.'),metric('Alpha',fmt(x.alpha,6),'intercepto','Componente médio não explicado pelo beta no modelo simples.'),metric('R²',pct(x.r2),'ajuste linear','Quanto da variação do alvo é explicada pela referência.'),metric('Corr. móvel',fmt(x.rolling,4),'última janela','Correlação na janela móvel mais recente.'),metric('Lead/Lag',String(x.leadLag.lag),'intervalos','Defasagem com maior correlação absoluta entre -5 e +5.')])).join('');
   modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-modal-panel" role="dialog" aria-modal="true"><header><div><strong>ANÁLISE COMPLETA</strong><small>'+r.observations+' observações · '+r.interval+' · '+date(r.rowsStart)+' → '+date(r.rowsEnd)+'</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-modal-body"><section><h3>O QUE FOI ANALISADO</h3><div class="analysis-explain"><b>Referência:</b> '+r.series[Object.keys(r.series)[0]].symbol+' · <b>Janela:</b> '+date(r.rowsStart)+' → '+date(r.rowsEnd)+' · <b>Observações:</b> '+r.observations+' · <b>Intervalo:</b> '+r.interval+'.<br>Os timestamps foram alinhados antes dos cálculos. Retornos usam log-retornos; volatilidade, Sharpe e Sortino são anualizados conforme o intervalo.</div></section><section><h3>PERFORMANCE E RISCO</h3><table><thead><tr><th>Ativo</th><th>Retorno</th><th>CAGR</th><th>Vol.</th><th>DD</th><th>Sharpe</th><th>Win rate</th></tr></thead><tbody>'+rows+'</tbody></table></section><section><h3>ESTATÍSTICAS AVANÇADAS</h3>'+advanced+'</section><section><h3>RELAÇÕES ESTATÍSTICAS</h3>'+rel+'</section><section><h3>INTERPRETAÇÃO</h3><div class="analysis-explain"><p><b>Correlação não é causalidade.</b> Mede associação estatística entre retornos.</p><p><b>Beta</b> mede sensibilidade relativa. <b>R²</b> mede o quanto o modelo linear simples explica da variação do alvo.</p><p><b>Lead/Lag</b> procura defasagens de até 5 intervalos. É diagnóstico exploratório, não prova de previsão.</p><p><b>Base 100 + log</b> permite comparar trajetórias com preços absolutos muito diferentes.</p></div></section></div></section>';
   const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);if(focusAdvanced)modal.querySelector('.analysis-stat-block')?.scrollIntoView();
 }
 async function run(){
   const activeSymbol=getActiveSymbol(),reference=document.querySelector('#analysis-reference')?.value||activeSymbol,checked=[...document.querySelectorAll('.analysis-asset:checked')].map(x=>x.value),symbols=[reference,...checked.filter(x=>x!==reference)];
   $('#analysis-status').textContent='ANALISANDO';$('#analysis-results').classList.add('is-hidden');$('#full-analysis').classList.add('is-hidden');$('#comparison-panel').classList.add('is-hidden');$('#analysis-context').classList.add('is-hidden');
   try{const interval=getInterval()||'1d',period=document.querySelector('#analysis-period')?.value||'full',returnMode=document.querySelector('#analysis-return')?.value||'log',rollingWindow=Number(document.querySelector('#analysis-window')?.value||30),depth=document.querySelector('#analysis-depth')?.value||'key',series=[];for(const key of symbols){const meta=assets[key],loaded=key===activeSymbol?{candles:getCandles()}:await dataClient.loadOrPopulate({provider:meta.provider,symbol:meta.providerSymbol||key,kind:'ohlcv',interval,currency:'USD'});const candles=normalizeCandles(loaded.candles);if(candles.length<10)throw new Error('Poucos dados para '+meta.symbol+'.');series.push({key,symbol:meta.symbol,name:meta.name,candles})}let rows=alignSeries(series);if(rows.length<10)throw new Error('Poucos timestamps comuns para esta análise.');if(period!=='full'){const days=Number(period),cutoff=rows.at(-1).timestamp-days*86400000;rows=rows.filter(r=>r.timestamp>=cutoff);if(rows.length<10)throw new Error('O período escolhido não possui observações suficientes para esta análise.')}state.rows=rows;state.markers={start:0,base:0,end:rows.length-1};const result=analyzeSeries(rows,series,interval,{returnMode,rollingWindow});result.periodDays=period;result.rowsStart=rows[0].timestamp;result.rowsEnd=rows.at(-1).timestamp;render(result,series);if(depth==='full')openModal(false);else if(depth==='advanced')openModal(true)}catch(error){console.error('[ORACULUM ANALYSIS]',error);$('#analysis-status').textContent='ERRO';$('#analysis-results').innerHTML='<div class="analysis-diagnostics"><p>'+error.message+'</p></div>';$('#analysis-results').classList.remove('is-hidden')}}
 const button=$('#analyze-assets');button?.addEventListener('click',run);$('#full-analysis')?.addEventListener('click',()=>openModal(false));
 const onResize=()=>{if(state.rows?.length){const selected=state.selected.map(k=>({...assets[k],key:k})).filter(Boolean);renderChart(state.rows,selected);renderMarkerTimeline()}};window.addEventListener('resize',onResize);return{run,destroy(){window.removeEventListener('resize',onResize)}};
}