/* ORACULUM — explicações científicas */
export const topicText={
 'Retorno':{title:'Retorno',what:'Variação do preço entre observações consecutivas ou ao longo da janela selecionada.',formula:"r_t = \\ln\\left(\\frac{P_t}{P_{t-1}}\\right)",interpret:'No modo logarítmico, retornos são aditivos ao longo do tempo e aproximam a variação percentual para movimentos pequenos.',limits:'O resultado depende da frequência, da série de preços utilizada e do tratamento de observações ausentes.'},
 'CAGR':{title:'CAGR',what:'Taxa composta anualizada que representa o crescimento equivalente ao longo do período.',formula:"\\mathrm{CAGR}=\\left(\\frac{P_f}{P_i}\\right)^{1/T}-1",interpret:'É uma taxa anual equivalente; não significa que o ativo tenha crescido de forma uniforme.',limits:'Pode ser pouco representativo em períodos curtos ou em séries muito voláteis.'},
 'Volatilidade':{title:'Volatilidade',what:'Medida da dispersão dos retornos. No Oraculum, é anualizada conforme a frequência da série.',formula:"\\sigma=\\sqrt{\\operatorname{Var}(r)}",interpret:'Maior volatilidade significa maior dispersão dos retornos, não necessariamente maior retorno esperado.',limits:'Volatilidade histórica não é uma previsão garantida da volatilidade futura.'},
 'Drawdown máximo':{title:'Drawdown máximo',what:'Maior queda observada de um pico até o vale subsequente.',formula:"DD_t=\\frac{P_t}{\\max_{u\\le t}(P_u)}-1",interpret:'Quantifica a pior perda relativa a partir de um máximo histórico da janela.',limits:'Não descreve sozinho a duração da recuperação nem a frequência dos drawdowns.'},
 'Sharpe':{title:'Índice de Sharpe',what:'Relaciona retorno médio ao risco medido pela volatilidade.',formula:"\\mathrm{Sharpe}=\\frac{E[r]-r_f}{\\sigma}",interpret:'No Oraculum, a interpretação é condicionada à convenção de risco/retorno usada pela implementação e à série escolhida.',limits:'A interpretação depende das hipóteses sobre distribuição, taxa livre de risco e período de estimação.'},
 'Sortino':{title:'Índice de Sortino',what:'Mede retorno ajustado pelo risco de queda, penalizando principalmente retornos abaixo do alvo.',formula:"\\mathrm{Sortino}=\\frac{E[r]-\\tau}{\\sigma_{\\mathrm{downside}}}",interpret:'É útil quando o foco é distinguir volatilidade desejável de risco negativo.',limits:'Resultado sensível ao alvo e à definição de downside utilizada.'},
 'Win rate':{title:'Win rate',what:'Proporção de observações com retorno positivo.',formula:"\\mathrm{Win\\ rate}=\\frac{N(r_t>0)}{N}",interpret:'Indica a frequência de períodos positivos, mas não o tamanho dos ganhos ou perdas.',limits:'Um win rate alto pode coexistir com perdas médias grandes.'},
 'ATH':{title:'ATH / ATL',what:'Maior ou menor preço observado dentro da amostra analisada.',formula:"\\mathrm{ATH}=\\max_t(P_t)\\qquad;\\qquad\\mathrm{ATL}=\\min_t(P_t)",interpret:'São estatísticas descritivas da janela, não estimativas de valor fundamental.',limits:'Mudar o período altera diretamente o máximo e o mínimo observados.'},
 'CORR.':{title:'Correlação de Pearson',what:'Mede a associação linear entre duas séries de retornos.',formula:"\\rho=\\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X\\sigma_Y}",interpret:'Valores próximos de +1 indicam associação linear positiva; próximos de −1, negativa; próximo de 0, pouca associação linear.',limits:'Correlação não implica causalidade e pode variar substancialmente ao longo do tempo.'},
 'BETA':{title:'Beta',what:'Mede a sensibilidade linear do retorno do ativo-alvo ao retorno da referência.',formula:"\\beta=\\frac{\\operatorname{Cov}(R_X,R_M)}{\\operatorname{Var}(R_M)}",interpret:'β > 1 indica maior sensibilidade que a referência; 0 < β < 1 indica menor sensibilidade.',limits:'É uma relação estatística dependente da amostra e da especificação; não é uma constante estrutural garantida.'},
 'R²':{title:'R²',what:'Mede a parcela da variação do alvo associada ao ajuste linear com a referência.',formula:"R^2=1-\\frac{\\mathrm{SSE}}{\\mathrm{SST}}",interpret:'Em uma regressão linear simples com intercepto, R² está relacionado ao quadrado da correlação.',limits:'Não mede causalidade nem garante validade fora da amostra.'},
 'LEAD/LAG':{title:'Lead/Lag',what:'Procura uma defasagem temporal na qual a associação entre as séries seja maior em valor absoluto.',formula:"\\rho_k=\\operatorname{Corr}(X_t,Y_{t+k})",interpret:'É um diagnóstico exploratório de temporalidade estatística.',limits:'Não constitui evidência de causalidade nem de poder preditivo.'},
 'MÉTODO':{title:'Método e desenho da investigação',what:'A análise deve ser lida como uma sequência reproduzível: dados → tratamento → transformação → estimação → diagnóstico → interpretação.',formula:'Dados → Alinhamento → Retornos → Estatística/Modelo → Diagnóstico → Robustez → Interpretação',interpret:'O mesmo conjunto de dados pode produzir resultados diferentes quando mudamos período, frequência, transformação ou especificação. Por isso esses parâmetros são parte do resultado.',limits:'Nenhum resultado estatístico elimina as limitações da amostra ou transforma associação em causalidade.'}
};
export function topicFor(label){const u=String(label).toUpperCase();if(u==='MÉTODO')return topicText['MÉTODO'];for(const k of Object.keys(topicText)){if(u.includes(k.toUpperCase()))return topicText[k]}return {title:label,what:'Estatística calculada a partir da amostra selecionada.',formula:'Consulte a especificação metodológica desta análise.',interpret:'O valor deve ser interpretado em conjunto com a amostra, período e método.',limits:'Resultados estatísticos são condicionados à especificação e aos dados utilizados.'}}
export function openInfo(label){
 const t=topicFor(label),modal=document.createElement('div');modal.className='analysis-info-modal';
 modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-info-panel" role="dialog" aria-modal="true"><header><div><strong>'+t.title+'</strong><small>EXPLICAÇÃO CIENTÍFICA</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-info-body"><section><h3>O QUE É</h3><p>'+t.what+'</p></section><section><h3>FORMULAÇÃO MATEMÁTICA</h3><div class="formula-box">\\['+t.formula+'\\]</div></section><section><h3>INTERPRETAÇÃO</h3><p>'+t.interpret+'</p></section><section><h3>LIMITAÇÕES</h3><p>'+t.limits+'</p></section></div></section>';
 const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([modal]);
}
