/* ORACULUM — explicações científicas */
export const topicText={
 'Retorno':{title:'Retorno',what:'Variação do preço entre observações consecutivas. O Oraculum usa retorno logarítmico por padrão e também permite retorno simples.',formula:"\\text{Log: }r_t=\\ln\\left(\\frac{P_t}{P_{t-1}}\\right)\\qquad\\text{Simples: }r_t=\\frac{P_t}{P_{t-1}}-1",interpret:'Retornos logarítmicos são aditivos ao longo do tempo: a soma dos retornos log equivale ao log da variação acumulada. O retorno simples representa diretamente a variação percentual do preço.',limits:'A interpretação depende da frequência, da série de preços e do tratamento de observações ausentes. Retornos não demonstram causalidade.'},
 'CAGR':{title:'CAGR',what:'Taxa composta anualizada que representa o crescimento equivalente entre o início e o fim da janela.',formula:"\\mathrm{CAGR}=\\left(\\frac{P_f}{P_i}\\right)^{1/T}-1,\\qquad T=\\text{anos decorridos}",interpret:'É uma taxa anual equivalente, não uma trajetória uniforme. O cálculo usa apenas o valor inicial, final e o tempo decorrido.',limits:'Pode esconder grande volatilidade, drawdowns e mudanças de regime. Em períodos curtos, sua interpretação pode ser instável.'},
 'Volatilidade':{title:'Volatilidade',what:'Mede a dispersão dos retornos. No Oraculum, o desvio-padrão amostral dos retornos é anualizado pela raiz da quantidade de períodos por ano.',formula:"s_r=\\sqrt{\\frac{1}{n-1}\\sum_{t=1}^{n}(r_t-\\bar r)^2}\\qquad\\sigma_{anual}=s_r\\sqrt{p}",interpret:'Maior volatilidade significa maior dispersão histórica dos retornos. Não significa, por si só, maior retorno esperado.',limits:'A anualização por raiz do tempo pressupõe uma convenção de escala que pode ser inadequada sob dependência temporal ou mudanças de regime. Volatilidade histórica não é previsão garantida.'},
 'Drawdown máximo':{title:'Drawdown máximo',what:'Maior queda observada de um pico histórico da própria janela até um ponto posterior.',formula:"DD_t=\\frac{P_t}{M_t}-1,\\qquad M_t=\\max_{u\\le t}P_u,\\qquad MDD=\\min_t DD_t",interpret:'O valor é normalmente negativo: por exemplo, −0,40 representa uma queda de 40% em relação ao pico anterior.',limits:'Não descreve sozinho a duração da recuperação, a frequência dos drawdowns ou o risco futuro. O resultado depende da janela.'},
 'Sharpe':{title:'Índice de Sharpe',what:'Relaciona retorno médio ao desvio-padrão dos retornos. A definição teórica desconta uma taxa livre de risco.',formula:"\\mathrm{Sharpe}_{teórico}=\\frac{E[r]-r_f}{\\sigma_r}\\qquad\\mathrm{Sharpe}_{Oraculum}=\\frac{\\bar r}{s_r}\\sqrt{p}",interpret:'Na implementação atual, o Oraculum não fornece uma série de taxa livre de risco: portanto calcula uma versão sem desconto de r_f e anualiza pela frequência.',limits:'O resultado depende da amostra, frequência e distribuição dos retornos. A versão sem r_f não deve ser interpretada como Sharpe completo quando uma taxa livre de risco relevante estiver disponível.'},
 'Sortino':{title:'Índice de Sortino',what:'Relaciona o retorno médio ao risco de queda abaixo de um alvo. A definição teórica usa um alvo explícito; a implementação atual usa a dispersão amostral dos retornos negativos.',formula:"\\mathrm{Sortino}_{teórico}=\\frac{E[r]-\\tau}{\\sigma_{down}}\\qquad\\mathrm{Sortino}_{Oraculum}=\\frac{\\bar r}{s(r<0)}\\sqrt{p}",interpret:'O foco é penalizar o risco negativo em vez de toda a volatilidade. No Oraculum, o alvo \\tau não é configurável atualmente e a implementação usa os retornos negativos para estimar o desvio-padrão downside.',limits:'A definição implementada é uma aproximação operacional, não todas as convenções acadêmicas do Sortino. O resultado é sensível à amostra e à quantidade de retornos negativos.'},
 'Win rate':{title:'Win rate',what:'Proporção de retornos positivos entre as observações de retorno disponíveis.',formula:"\\mathrm{Win\\ rate}=\\frac{N(r_t>0)}{N}",interpret:'Indica a frequência de períodos positivos, mas não informa o tamanho médio dos ganhos e perdas.',limits:'Um win rate alto pode coexistir com perdas médias grandes; por isso deve ser analisado junto com magnitude dos retornos, drawdown e distribuição.'},
 'ATH':{title:'ATH / ATL',what:'Maior e menor preço observados dentro da amostra analisada.',formula:"\\mathrm{ATH}=\\max_t P_t\\qquad\\mathrm{ATL}=\\min_t P_t",interpret:'São estatísticas descritivas da janela, não estimativas de valor fundamental.',limits:'Alterar o período altera diretamente os máximos e mínimos observados.'},
 'CORR.':{title:'Correlação de Pearson',what:'Mede a associação linear entre duas séries de retornos.',formula:"\\rho_{XY}=\\frac{\\operatorname{Cov}(X,Y)}{\\sigma_X\\sigma_Y}",interpret:'Valores próximos de +1 indicam associação linear positiva; próximos de −1, negativa; próximos de 0 indicam pouca associação linear.',limits:'Correlação não implica causalidade. Pode variar ao longo do tempo e pode ser afetada por outliers, regimes e alinhamento temporal.'},
 'BETA':{title:'Beta',what:'Mede a sensibilidade linear do retorno do ativo-alvo ao retorno de uma referência.',formula:"\\beta=\\frac{\\operatorname{Cov}(R_X,R_M)}{\\operatorname{Var}(R_M)}",interpret:'Em uma regressão com intercepto, β representa a variação média esperada em X associada a uma unidade de variação em M. β>1 indica maior sensibilidade; 0<β<1, menor sensibilidade.',limits:'É uma estimativa dependente da amostra e da especificação. Não é uma constante estrutural garantida e não implica causalidade.'},
 'R²':{title:'R² e R² ajustado',what:'R² mede quanto da variação observada do alvo é contabilizada pelo ajuste linear. O R² ajustado penaliza a inclusão de variáveis explicativas que não acrescentam informação suficiente.',formula:"R^2=1-\\frac{SSE}{SST}\\qquad R^2_{aj}=1-(1-R^2)\\frac{n-1}{n-k-1}",interpret:'Quanto maior o R², maior a parcela da variação amostral associada ao modelo. O R² ajustado é mais apropriado para comparar modelos com diferentes números de explicadores.',limits:'R² não mede causalidade nem garante capacidade preditiva fora da amostra. Um R² alto pode resultar de especificação inadequada ou variáveis correlacionadas.'},
 'LEAD/LAG':{title:'Lead / Lag',what:'Procura em qual defasagem temporal a associação entre duas séries é maior em valor absoluto.',formula:"\\rho_k=\\operatorname{Corr}(X_t,Y_{t+k}),\\qquad k\\in[-K,K]",interpret:'O resultado é exploratório: identifica uma defasagem em que as séries apresentam maior associação linear.',limits:'A escolha da maior correlação não prova causalidade, precedência econômica nem poder preditivo. Múltiplas defasagens também aumentam o risco de encontrar associações por acaso.'},
 'MODELO MULTIVARIADO':{title:'Modelo multivariado',what:'Regressão linear que estima quanto os retornos do ativo-alvo estão associados conjuntamente às variáveis selecionadas.',formula:"R_{BTC,t}=\\alpha+\\beta_1X_{1,t}+\\cdots+\\beta_kX_{k,t}+\\varepsilon_t\\qquad\\hat\\beta=(X'X)^{-1}X'Y",interpret:'Cada β mede a associação marginal estimada com o alvo mantendo as demais variáveis do modelo constantes. O modelo explica retornos, não demonstra que os fatores causam o preço do BTC.',limits:'A interpretação depende de alinhamento temporal, especificação, tamanho da amostra e hipóteses sobre os resíduos. Multicolinearidade, heterocedasticidade e autocorrelação podem distorcer a inferência convencional.'},
 'R² AJUSTADO':{title:'R² ajustado',what:'Versão do R² que penaliza a inclusão de variáveis explicativas em relação ao tamanho da amostra.',formula:"R^2_{aj}=1-(1-R^2)\\frac{n-1}{n-k-1}",interpret:'Pode diminuir quando uma nova variável é adicionada e não melhora suficientemente o ajuste.',limits:'Não é uma prova de causalidade nem uma garantia de desempenho fora da amostra.'},
 'ERRO-PADRÃO':{title:'Erro-padrão, t e p',what:'O erro-padrão mede a incerteza amostral de uma estimativa. O teste t compara a estimativa com seu erro-padrão.',formula:"t_j=\\frac{\\hat\\beta_j}{SE(\\hat\\beta_j)}",interpret:'Em condições clássicas, valores absolutos maiores de t fornecem mais evidência contra a hipótese de β_j=0. O p-valor depende da distribuição de referência e das hipóteses adotadas.',limits:'Os os p-valores OLS usam a distribuição t com os graus de liberdade do modelo; a inferência HAC usa aproximação assintótica e deve ser interpretada com cautela em amostras pequenas.'},
 'DURBIN-WATSON':{title:'Durbin-Watson',what:'Diagnóstico exploratório de autocorrelação serial de primeira ordem nos resíduos.',formula:"DW=\\frac{\\sum_{t=2}^{n}(e_t-e_{t-1})^2}{\\sum_{t=1}^{n}e_t^2}",interpret:'Valores próximos de 2 são compatíveis com pouca autocorrelação de primeira ordem; abaixo de 2 sugerem autocorrelação positiva e acima de 2, negativa, como regra heurística.',limits:'Não é um teste completo para todos os tipos de dependência temporal e sua interpretação depende do modelo e da amostra.'},
 'VARIANCE RATIO':{title:'Razão de variâncias dos resíduos',what:'Compara a variância estimada dos resíduos na primeira e na segunda metade da amostra.',formula:"VR=\\frac{\\max(s_1^2,s_2^2)}{\\min(s_1^2,s_2^2)}",interpret:'Valor próximo de 1 indica variâncias semelhantes entre as duas metades. Valores maiores sugerem possível mudança na dispersão dos resíduos.',limits:'É um diagnóstico simples, não um teste formal de heterocedasticidade ou quebra estrutural.'},
 'Assimetria':{title:'Assimetria',what:'Mede a assimetria da distribuição dos retornos em torno da média.',formula:"\gamma_1=\frac{n}{(n-1)(n-2)}\sum\left(\frac{x_i-\bar x}{s}\right)^3",interpret:'Valores positivos indicam cauda mais longa à direita; negativos, à esquerda. Próximo de zero indica maior simetria.',limits:'É sensível a valores extremos e pode ser instável em amostras pequenas.'},
 'Curtose excedente':{title:'Curtose excedente',what:'Mede a espessura das caudas em relação à normal, usando curtose menos 3.',formula:"g_2=\frac{n(n+1)}{(n-1)(n-2)(n-3)}\sum z_i^4-\frac{3(n-1)^2}{(n-2)(n-3)}",interpret:'Valor positivo sugere caudas mais pesadas que a normal; negativo, mais leves.',limits:'Convenções de curtose variam; o Oraculum informa explicitamente que usa curtose excedente.'},
 'VaR':{title:'Value at Risk',what:'Quantil histórico de perda para um nível de confiança definido.',formula:"VaR_\alpha=-Q_{1-\alpha}(r)",interpret:'VaR 95% é a perda histórica que só é superada em aproximadamente 5% das observações da amostra.',limits:'Não informa a magnitude média das perdas além do quantil. Por isso o ES deve ser analisado junto.'},
 'ES':{title:'Expected Shortfall',what:'Perda média na cauda além do VaR para o nível de confiança escolhido.',formula:"ES_\alpha=-E[r\mid r\le Q_{1-\alpha}]",interpret:'É mais informativo sobre a severidade da cauda do que o VaR, porque considera as perdas além do ponto de corte.',limits:'É histórico e depende fortemente da quantidade e qualidade das observações extremas.'},
 'Calmar':{title:'Índice de Calmar',what:'Relaciona CAGR ao drawdown máximo absoluto.',formula:"Calmar=\frac{CAGR}{|MDD|}",interpret:'Maior valor indica maior crescimento anualizado relativo à pior queda histórica.',limits:'Depende da janela e usa apenas o pior drawdown, ignorando a distribuição completa do risco.'},
 'INTERVALO DE CONFIANÇA':{title:'Intervalo de confiança',what:'Faixa de incerteza amostral para um coeficiente sob as hipóteses do modelo.',formula:"\hat\beta_j\pm t_{1-\alpha/2,df}SE(\hat\beta_j)",interpret:'Um IC 95% descreve o conjunto de valores compatíveis com o procedimento inferencial sob as hipóteses adotadas.',limits:'Não é a probabilidade de o parâmetro estar dentro do intervalo depois que o intervalo foi calculado.'},
 'HAC':{title:'Erro-padrão robusto HAC',what:'Erro-padrão Newey-West que permite heterocedasticidade e autocorrelação de forma não paramétrica até uma janela de defasagens.',formula:"\widehat V_{HAC}=(X'X)^{-1}\widehat S(X'X)^{-1}",interpret:'É preferível à inferência OLS convencional quando resíduos de séries temporais podem apresentar dependência e variância não constante.',limits:'Não corrige especificação errada, viés de variável omitida, endogeneidade ou look-ahead bias.'},
 'VIF':{title:'VIF — fator de inflação da variância',what:'Diagnóstico de multicolinearidade entre variáveis explicativas.',formula:"VIF_j=\frac{1}{1-R_j^2}",interpret:'Quanto maior o VIF, maior a redundância linear da variável com as demais, tornando os coeficientes menos estáveis.',limits:'VIF diagnostica colinearidade, não causalidade nem qualidade geral do modelo.'},
 'MÉTODO':{title:'Método e desenho da investigação',what:'A análise deve ser lida como uma sequência reproduzível: dados → alinhamento → transformação → estimação → diagnóstico → robustez → interpretação.',formula:'Dados → Alinhamento → Retornos → Estatística/Modelo → Diagnóstico → Robustez → Interpretação',interpret:'O mesmo conjunto de dados pode produzir resultados diferentes quando mudamos período, frequência, transformação ou especificação. Esses parâmetros fazem parte do resultado.',limits:'Nenhum resultado estatístico elimina limitações da amostra ou transforma associação em causalidade.'}
};
export function topicFor(label){const u=String(label).toUpperCase();if(u==='MÉTODO')return topicText['MÉTODO'];for(const k of Object.keys(topicText)){if(u.includes(k.toUpperCase()))return topicText[k]}return {title:label,what:'Estatística calculada a partir da amostra selecionada.',formula:'Consulte a especificação metodológica desta análise.',interpret:'O valor deve ser interpretado em conjunto com a amostra, período e método.',limits:'Resultados estatísticos são condicionados à especificação e aos dados utilizados.'}}
export function openInfo(label){
 const t=topicFor(label),modal=document.createElement('div');modal.className='analysis-info-modal';
 modal.innerHTML='<div class="analysis-modal-backdrop"></div><section class="analysis-info-panel" role="dialog" aria-modal="true"><header><div><strong>'+t.title+'</strong><small>EXPLICAÇÃO CIENTÍFICA</small></div><button class="analysis-close" aria-label="Fechar">×</button></header><div class="analysis-info-body"><section><h3>O QUE É</h3><p>'+t.what+'</p></section><section><h3>FORMULAÇÃO MATEMÁTICA</h3><div class="formula-box">\\['+t.formula+'\\]</div></section><section><h3>INTERPRETAÇÃO</h3><p>'+t.interpret+'</p></section><section><h3>LIMITAÇÕES</h3><p>'+t.limits+'</p></section></div></section>';
 const close=()=>modal.remove();modal.querySelector('.analysis-close').onclick=close;modal.querySelector('.analysis-modal-backdrop').onclick=close;document.body.appendChild(modal);if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([modal]);
}
